server:
  port: 8080
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: localhost:8846/oauth/key
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - StripPrefix=1
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/oauth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/roles/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**,/api/categories/**