server:
  port: 8080
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: localhost:8846/oauth/key
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - StripPrefix=1
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/oauth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - name: Path
              args:
              - /api/users/**
              - /api/roles/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - name: Path
              args:
                - /api/courses/**
                - /api/categories/**
                - /api/chapters/**
                - /api/questions/**
                - /api/answers/**
                - /api/notes/**
                - /api/evaluations/**